import React, { createContext, useState, useContext, ReactNode } from 'react';

// Define available languages
export type Language = 'en' | 'es' | 'fr' | 'zh' | 'hi';

// Translations for different languages
const translations = {
  en: {
    home: 'Home',
    dashboard: 'Dashboard',
    programming: 'Programming',
    resources: 'Resources',
    interview: 'Interview',
    videoCall: 'Video Call',
    games: 'Games',
    login: 'Login',
    logout: 'Logout',
    welcomeBack: 'Welcome Back',
    getStarted: 'Get Started',
    academicSuccess: 'Your Path to Academic Success',
    accessiblePlatform: 'An inclusive learning platform designed for all students, with special focus on accessibility for children with disabilities.',
    exploreResources: 'Explore Resources',
    goToDashboard: 'Go to Dashboard',
    learningResources: 'Learning Resources',
    curatedResources: 'Curated resources to help you in your learning journey.',
    generalLearning: 'General Learning',
    programmingResources: 'Programming',
    interviewPrep: 'Interview Prep',
    // Games translations
    memoryChallenge: 'Memory Challenge',
    mathAdventures: 'Math Adventures',
    spellingBee: 'Spelling Bee',
    startGame: 'Start Game',
    playAgain: 'Play Again',
    score: 'Score',
    timer: 'Timer',
    question: 'Question',
    submit: 'Submit',
    correct: 'Correct!',
    incorrect: 'Incorrect',
    theAnswerWas: 'The answer was',
    gameOver: 'Game Over',
    perfectScore: 'Perfect score!',
    changeDifficulty: 'Change Difficulty',
    backToMenu: 'Back to Menu',
    moves: 'Moves',
    word: 'Word',
    of: 'of',
    yourScore: 'Your Score',
    youSpelled: 'You spelled',
    outOf: 'out of',
    wordsCorrectly: 'words correctly',
    timeTaken: 'Time taken',
    changeLevel: 'Change Level',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    theCorrectSpellingIs: 'The correct spelling is',
    // Sign language translations
    signLanguageTranslator: 'Sign Language Translator',
    camera: 'Camera',
    translation: 'Translation',
    enableCamera: 'Enable Camera',
    translatingSignLanguage: 'Translating sign language...',
    translatedText: 'Translated text',
    translationPlaceholder: 'Sign language translation will appear here...',
    cameraEnabled: 'Camera Enabled',
    signLanguageReady: 'Sign language translator is ready to use',
    cameraError: 'Camera Error',
    cameraPermissionDenied: 'Camera permission was denied',
    translationStarted: 'Sign language translation started',
    translationStopped: 'Sign language translation stopped',
    howItWorks: 'How It Works',
    // Accessibility
    accessibility: 'Accessibility',
    textToSpeech: 'Text to Speech',
    voiceToText: 'Voice to Text',
    highContrast: 'High Contrast',
    largeText: 'Large Text',
    screenReader: 'Screen Reader',
    dyslexicFont: 'Dyslexic Font',
    colorBlindMode: 'Color Blind Mode',
  },
  es: {
    home: 'Inicio',
    dashboard: 'Panel',
    programming: 'Programación',
    resources: 'Recursos',
    interview: 'Entrevista',
    videoCall: 'Videollamada',
    games: 'Juegos',
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    welcomeBack: 'Bienvenido de nuevo',
    getStarted: 'Comenzar',
    academicSuccess: 'Tu camino hacia el éxito académico',
    accessiblePlatform: 'Una plataforma de aprendizaje inclusiva diseñada para todos los estudiantes, con especial atención a la accesibilidad para niños con discapacidades.',
    exploreResources: 'Explorar recursos',
    goToDashboard: 'Ir al panel',
    learningResources: 'Recursos de aprendizaje',
    curatedResources: 'Recursos seleccionados para ayudarte en tu viaje de aprendizaje.',
    generalLearning: 'Aprendizaje general',
    programmingResources: 'Programación',
    interviewPrep: 'Preparación para entrevistas',
    // Games translations
    memoryChallenge: 'Desafío de Memoria',
    mathAdventures: 'Aventuras Matemáticas',
    spellingBee: 'Concurso de Ortografía',
    startGame: 'Iniciar Juego',
    playAgain: 'Jugar de Nuevo',
    score: 'Puntuación',
    timer: 'Tiempo',
    question: 'Pregunta',
    submit: 'Enviar',
    correct: '¡Correcto!',
    incorrect: 'Incorrecto',
    theAnswerWas: 'La respuesta era',
    gameOver: 'Juego Terminado',
    perfectScore: '¡Puntuación perfecta!',
    changeDifficulty: 'Cambiar Dificultad',
    backToMenu: 'Volver al Menú',
    moves: 'Movimientos',
    word: 'Palabra',
    of: 'de',
    yourScore: 'Tu Puntuación',
    youSpelled: 'Has escrito',
    outOf: 'de',
    wordsCorrectly: 'palabras correctamente',
    timeTaken: 'Tiempo empleado',
    changeLevel: 'Cambiar Nivel',
    easy: 'Fácil',
    medium: 'Medio',
    hard: 'Difícil',
    theCorrectSpellingIs: 'La ortografía correcta es',
    // Sign language translations
    signLanguageTranslator: 'Traductor de Lenguaje de Señas',
    camera: 'Cámara',
    translation: 'Traducción',
    enableCamera: 'Habilitar Cámara',
    translatingSignLanguage: 'Traduciendo lenguaje de señas...',
    translatedText: 'Texto traducido',
    translationPlaceholder: 'La traducción del lenguaje de señas aparecerá aquí...',
    cameraEnabled: 'Cámara Habilitada',
    signLanguageReady: 'El traductor de lenguaje de señas está listo para usar',
    cameraError: 'Error de Cámara',
    cameraPermissionDenied: 'Se denegó el permiso de la cámara',
    translationStarted: 'Traducción de lenguaje de señas iniciada',
    translationStopped: 'Traducción de lenguaje de señas detenida',
    // Accessibility
    accessibility: 'Accesibilidad',
    textToSpeech: 'Texto a Voz',
    voiceToText: 'Voz a Texto',
    highContrast: 'Alto Contraste',
    largeText: 'Texto Grande',
    screenReader: 'Lector de Pantalla',
    dyslexicFont: 'Fuente para Dislexia',
    colorBlindMode: 'Modo Daltónico',
  },
  fr: {
    home: 'Accueil',
    dashboard: 'Tableau de bord',
    programming: 'Programmation',
    resources: 'Ressources',
    interview: 'Entretien',
    videoCall: 'Appel vidéo',
    games: 'Jeux',
    login: 'Connexion',
    logout: 'Déconnexion',
    welcomeBack: 'Bienvenue à nouveau',
    getStarted: 'Commencer',
    academicSuccess: 'Votre chemin vers la réussite académique',
    accessiblePlatform: 'Une plateforme d\'apprentissage inclusive conçue pour tous les étudiants, avec un accent particulier sur l\'accessibilité pour les enfants handicapés.',
    exploreResources: 'Explorer les ressources',
    goToDashboard: 'Aller au tableau de bord',
    learningResources: 'Ressources d\'apprentissage',
    curatedResources: 'Ressources sélectionnées pour vous aider dans votre parcours d\'apprentissage.',
    generalLearning: 'Apprentissage général',
    programmingResources: 'Programmation',
    interviewPrep: 'Préparation aux entretiens',
    // Games translations
    memoryChallenge: 'Défi de Mémoire',
    mathAdventures: 'Aventures Mathématiques',
    spellingBee: 'Concours d\'Orthographe',
    startGame: 'Commencer le Jeu',
    playAgain: 'Rejouer',
    score: 'Score',
    timer: 'Chronomètre',
    question: 'Question',
    submit: 'Soumettre',
    correct: 'Correct !',
    incorrect: 'Incorrect',
    theAnswerWas: 'La réponse était',
    gameOver: 'Jeu Terminé',
    perfectScore: 'Score parfait !',
    changeDifficulty: 'Changer la Difficulté',
    backToMenu: 'Retour au Menu',
    moves: 'Mouvements',
    word: 'Mot',
    of: 'de',
    yourScore: 'Votre Score',
    youSpelled: 'Vous avez épelé',
    outOf: 'sur',
    wordsCorrectly: 'mots correctement',
    timeTaken: 'Temps utilisé',
    changeLevel: 'Changer de Niveau',
    easy: 'Facile',
    medium: 'Moyen',
    hard: 'Difficile',
    theCorrectSpellingIs: 'L\'orthographe correcte est',
    // Sign language translations
    signLanguageTranslator: 'Traducteur de Langue des Signes',
    camera: 'Caméra',
    translation: 'Traduction',
    enableCamera: 'Activer la Caméra',
    translatingSignLanguage: 'Traduction de la langue des signes...',
    translatedText: 'Texte traduit',
    translationPlaceholder: 'La traduction de la langue des signes apparaîtra ici...',
    cameraEnabled: 'Caméra Activée',
    signLanguageReady: 'Le traducteur de langue des signes est prêt à être utilisé',
    cameraError: 'Erreur de Caméra',
    cameraPermissionDenied: 'L\'autorisation de la caméra a été refusée',
    translationStarted: 'Traduction de la langue des signes commencée',
    translationStopped: 'Traduction de la langue des signes arrêtée',
    // Accessibility
    accessibility: 'Accessibilité',
    textToSpeech: 'Texte à Parole',
    voiceToText: 'Parole à Texte',
    highContrast: 'Contraste Élevé',
    largeText: 'Texte Large',
    screenReader: 'Lecteur d\'Écran',
    dyslexicFont: 'Police pour Dyslexie',
    colorBlindMode: 'Mode Daltonien',
  },
  zh: {
    home: '首页',
    dashboard: '仪表板',
    programming: '编程',
    resources: '资源',
    interview: '面试',
    videoCall: '视频通话',
    games: '游戏',
    login: '登录',
    logout: '登出',
    welcomeBack: '欢迎回来',
    getStarted: '开始使用',
    academicSuccess: '您通往学术成功的道路',
    accessiblePlatform: '为所有学生设计的包容性学习平台，特别关注残障儿童的无障碍设施。',
    exploreResources: '探索资源',
    goToDashboard: '前往仪表板',
    learningResources: '学习资源',
    curatedResources: '精心策划的资源，帮助您的学习之旅。',
    generalLearning: '通用学习',
    programmingResources: '编程',
    interviewPrep: '面试准备',
    // Games translations
    memoryChallenge: '记忆挑战',
    mathAdventures: '数学冒险',
    spellingBee: '拼写竞赛',
    startGame: '开始游戏',
    playAgain: '再玩一次',
    score: '分数',
    timer: '计时器',
    question: '问题',
    submit: '提交',
    correct: '正确！',
    incorrect: '不正确',
    theAnswerWas: '正确答案是',
    gameOver: '游戏结束',
    perfectScore: '完美分数！',
    changeDifficulty: '更改难度',
    backToMenu: '返回菜单',
    moves: '移动次数',
    word: '单词',
    of: '的',
    yourScore: '您的分数',
    youSpelled: '您拼写了',
    outOf: '中的',
    wordsCorrectly: '个单词正确',
    timeTaken: '用时',
    changeLevel: '更改级别',
    easy: '简单',
    medium: '中等',
    hard: '困难',
    theCorrectSpellingIs: '正确的拼写是',
    // Sign language translations
    signLanguageTranslator: '手语翻译器',
    camera: '摄像头',
    translation: '翻译',
    enableCamera: '启用摄像头',
    translatingSignLanguage: '正在翻译手语...',
    translatedText: '翻译文本',
    translationPlaceholder: '手语翻译将显示在这里...',
    cameraEnabled: '摄像头已启用',
    signLanguageReady: '手语翻译器已准备好使用',
    cameraError: '摄像头错误',
    cameraPermissionDenied: '摄像头权限被拒绝',
    translationStarted: '手语翻译已开始',
    translationStopped: '手语翻译已停止',
    // Accessibility
    accessibility: '无障碍',
    textToSpeech: '文字转语音',
    voiceToText: '语音转文字',
    highContrast: '高对比度',
    largeText: '大字体',
    screenReader: '屏幕阅读器',
    dyslexicFont: '阅读障碍字体',
    colorBlindMode: '色盲模式',
  },
  hi: {
    home: 'होम',
    dashboard: 'डैशबोर्ड',
    programming: 'प्रोग्रामिंग',
    resources: 'संसाधन',
    interview: 'साक्षात्कार',
    videoCall: 'वीडियो कॉल',
    games: 'गेम्स',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    welcomeBack: 'वापसी पर स्वागत है',
    getStarted: 'शुरू करें',
    academicSuccess: 'आपका अकादमिक सफलता का मार्ग',
    accessiblePlatform: 'सभी छात्रों के लिए डिज़ाइन किया गया एक समावेशी शिक्षण मंच, विशेष रूप से विकलांग बच्चों के लिए सुलभता पर ध्यान केंद्रित।',
    exploreResources: 'संसाधन एक्सप्लोर करें',
    goToDashboard: 'डैशबोर्ड पर जाएं',
    learningResources: 'शिक्षण संसाधन',
    curatedResources: 'आपकी शिक्षा यात्रा में मदद करने के लिए क्यूरेटेड संसाधन।',
    generalLearning: 'सामान्य शिक्षा',
    programmingResources: 'प्रोग्रामिंग',
    interviewPrep: 'साक्षात्कार की तैयारी',
    // Games translations
    memoryChallenge: 'मेमोरी चैलेंज',
    mathAdventures: 'गणित की रोमांच',
    spellingBee: 'वर्तनी प्रतियोगिता',
    startGame: 'गेम शुरू करें',
    playAgain: 'फिर से खेलें',
    score: 'स्कोर',
    timer: 'टाइमर',
    question: 'प्रश्न',
    submit: 'जमा करें',
    correct: 'सही!',
    incorrect: 'गलत',
    theAnswerWas: 'सही उत्तर था',
    gameOver: 'खेल समाप्त',
    perfectScore: 'परफेक्ट स्कोर!',
    changeDifficulty: 'कठिनाई बदलें',
    backToMenu: 'मेनू पर वापस जाएं',
    moves: 'चालें',
    word: 'शब्द',
    of: 'का',
    yourScore: 'आपका स्कोर',
    youSpelled: 'आपने सही वर्तनी की',
    outOf: 'में से',
    wordsCorrectly: 'शब्द सही',
    timeTaken: 'लिया गया समय',
    changeLevel: 'स्तर बदलें',
    easy: 'आसान',
    medium: 'मध्यम',
    hard: 'कठिन',
    theCorrectSpellingIs: 'सही वर्तनी है',
    // Sign language translations
    signLanguageTranslator: 'सांकेतिक भाषा अनुवादक',
    camera: 'कैमरा',
    translation: 'अनुवाद',
    enableCamera: 'कैमरा सक्षम करें',
    translatingSignLanguage: 'सांकेतिक भाषा का अनुवाद कर रहा है...',
    translatedText: 'अनुवादित पाठ',
    translationPlaceholder: 'सांकेतिक भाषा का अनुवाद यहां दिखाई देगा...',
    cameraEnabled: 'कैमरा सक्षम है',
    signLanguageReady: 'सांकेतिक भाषा अनुवादक उपयोग के लिए तैयार है',
    cameraError: 'कैमरा त्रुटि',
    cameraPermissionDenied: 'कैमरा अनुमति अस्वीकृत की गई',
    translationStarted: 'सांकेतिक भाषा अनुवाद शुरू हुआ',
    translationStopped: 'सांकेतिक भाषा अनुवाद रुका',
    // Accessibility
    accessibility: 'पहुंच',
    textToSpeech: 'पाठ से वाणी',
    voiceToText: 'वाणी से पाठ',
    highContrast: 'उच्च कंट्रास्ट',
    largeText: 'बड़ा पाठ',
    screenReader: 'स्क्रीन रीडर',
    dyslexicFont: 'डिस्लेक्सिक फॉन्ट',
    colorBlindMode: 'रंग अंधा मोड',
  }
};

// Type for our context
type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof typeof translations.en) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Translation function
  const t = (key: keyof typeof translations.en): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
